-- ============================================================
-- VIZME V5 - Migration 04: dashboard_blueprints
-- Sprint 1 - DB Foundation
-- Structural description of the dashboard (blocks + layout).
-- Generated by Opus, rendered by code without further AI calls.
-- ============================================================

CREATE TABLE dashboard_blueprints (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id         uuid REFERENCES projects(id) ON DELETE CASCADE,
  schema_id          uuid REFERENCES business_schemas(id) ON DELETE CASCADE,
  version            int NOT NULL DEFAULT 1,
  layout             jsonb NOT NULL,
  blocks             jsonb NOT NULL,
  is_active          boolean DEFAULT true,
  regenerated_reason text,
  created_at         timestamptz DEFAULT now()
);

CREATE INDEX idx_db_project_active
  ON dashboard_blueprints(project_id, is_active);

ALTER TABLE dashboard_blueprints ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users view blueprints of own projects"
  ON dashboard_blueprints FOR SELECT USING (project_id IN (
    SELECT id FROM projects WHERE user_id = auth.uid()
  ));

CREATE POLICY "Users create blueprints in own projects"
  ON dashboard_blueprints FOR INSERT WITH CHECK (project_id IN (
    SELECT id FROM projects WHERE user_id = auth.uid()
  ));

CREATE POLICY "Users update own blueprints"
  ON dashboard_blueprints FOR UPDATE USING (project_id IN (
    SELECT id FROM projects WHERE user_id = auth.uid()
  ));

CREATE POLICY "Users delete own blueprints"
  ON dashboard_blueprints FOR DELETE USING (project_id IN (
    SELECT id FROM projects WHERE user_id = auth.uid()
  ));
