-- ============================================================
-- VIZME V5 - Migration 06: insights
-- Sprint 1 - DB Foundation
-- Persisted narrative insights generated by Sonnet (weekly)
-- and Opus (monthly FODA / predictions).
-- ============================================================

CREATE TABLE insights (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id    uuid REFERENCES projects(id) ON DELETE CASCADE,
  type          text NOT NULL CHECK (type IN ('weekly','monthly','alert','anomaly')),
  title         text NOT NULL,
  content       text NOT NULL,
  data_snapshot jsonb,
  model_used    text,
  generated_at  timestamptz DEFAULT now(),
  read_at       timestamptz,
  priority      int DEFAULT 0
);

CREATE INDEX idx_insights_project_date
  ON insights(project_id, generated_at DESC);

CREATE INDEX idx_insights_project_unread
  ON insights(project_id, read_at) WHERE read_at IS NULL;

ALTER TABLE insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users view insights of own projects"
  ON insights FOR SELECT USING (project_id IN (
    SELECT id FROM projects WHERE user_id = auth.uid()
  ));

CREATE POLICY "Users insert insights in own projects"
  ON insights FOR INSERT WITH CHECK (project_id IN (
    SELECT id FROM projects WHERE user_id = auth.uid()
  ));

CREATE POLICY "Users update own insights"
  ON insights FOR UPDATE USING (project_id IN (
    SELECT id FROM projects WHERE user_id = auth.uid()
  ));

CREATE POLICY "Users delete own insights"
  ON insights FOR DELETE USING (project_id IN (
    SELECT id FROM projects WHERE user_id = auth.uid()
  ));
