// ============================================================
// VIZME V5 — dashboardBlueprintsRepo
// Blueprint = estructura del dashboard (bloques + layout).
// Generated by Opus, rendered by code.
// ============================================================

import { supabase } from '../supabase';
import type { DashboardBlueprint } from '../v5types';

export const dashboardBlueprintsRepo = {
  async getActive(projectId: string): Promise<DashboardBlueprint | null> {
    const { data, error } = await supabase
      .from('dashboard_blueprints')
      .select('*')
      .eq('project_id', projectId)
      .eq('is_active', true)
      .maybeSingle();
    if (error) throw error;
    return (data as DashboardBlueprint | null) ?? null;
  },

  async listVersions(projectId: string): Promise<DashboardBlueprint[]> {
    const { data, error } = await supabase
      .from('dashboard_blueprints')
      .select('*')
      .eq('project_id', projectId)
      .order('version', { ascending: false });
    if (error) throw error;
    return (data ?? []) as DashboardBlueprint[];
  },

  async createNewVersion(
    input: Omit<DashboardBlueprint, 'id' | 'created_at' | 'is_active'>
  ): Promise<DashboardBlueprint> {
    await supabase
      .from('dashboard_blueprints')
      .update({ is_active: false })
      .eq('project_id', input.project_id)
      .eq('is_active', true);

    const { data, error } = await supabase
      .from('dashboard_blueprints')
      .insert({ ...input, is_active: true })
      .select()
      .single();
    if (error) throw error;
    return data as DashboardBlueprint;
  },
};
