// ============================================================
// VIZME V5 — Domain types (single source of truth)
// Generated by Opus, consumed by repos / UI / Edge Functions.
// ============================================================

// ---------- Business Schema (Layer 1: Modelado) ----------

export type BusinessIdentity = {
  industry: string;
  sub_industry?: string;
  business_model: string;
  size: 'micro' | 'small' | 'medium' | 'large';
  location?: { country: string; state?: string; city?: string };
  language: string;
  currency: string;
};

export type Entity = {
  id: string;
  name: string;
  type: 'transactional' | 'master' | 'reference';
  fields: Array<{
    name: string;
    type: 'string' | 'number' | 'date' | 'boolean' | 'enum';
    required?: boolean;
    enum_values?: string[];
  }>;
};

export type Metric = {
  id: string;
  name: string;
  description: string;
  formula: string;
  unit: string;
  aggregation: 'sum' | 'avg' | 'count' | 'min' | 'max' | 'ratio';
  format: 'currency' | 'number' | 'percent' | 'duration';
  good_direction: 'up' | 'down';
  expected_range?: { min: number; max: number };
};

export type Dimension = {
  id: string;
  name: string;
  type: 'time' | 'category' | 'geo';
  hierarchy?: string[];
};

export type ExtractionRule = {
  source_pattern: string;
  target_entity: string;
  field_mappings: Record<string, string>;
  validations?: Array<{ field: string; rule: string }>;
};

export type ExternalSource = {
  type: 'google_places' | 'inegi' | 'denue' | 'banxico' | 'google_trends' | 'openweather' | 'sat_dof';
  query_template: string;
  refresh_interval_days: number;
  enabled: boolean;
};

export type BusinessSchema = {
  id: string;
  project_id: string;
  version: number;
  business_identity: BusinessIdentity;
  entities: Entity[];
  metrics: Metric[];
  dimensions: Dimension[];
  extraction_rules: ExtractionRule[];
  external_sources: ExternalSource[];
  created_at: string;
  is_active: boolean;
};

// ---------- Dashboard Blueprint (Layer 3: Dashboard Vivo) ----------

type BlockBase = {
  id: string;
  title: string;
  position: { x: number; y: number; w: number; h: number };
};

export type KPIBlock = BlockBase & {
  type: 'kpi';
  metric_id: string;
  comparison?: 'previous_period' | 'previous_year' | 'target';
  target_value?: number;
};

export type LineChartBlock = BlockBase & {
  type: 'line_chart';
  metric_ids: string[];
  dimension_id: string;
  time_range: 'last_7d' | 'last_30d' | 'last_90d' | 'last_year' | 'all';
};

export type BarChartBlock = BlockBase & {
  type: 'bar_chart';
  metric_id: string;
  group_by_dimension_id: string;
  orientation: 'vertical' | 'horizontal';
  limit?: number;
};

export type PieChartBlock = BlockBase & {
  type: 'pie_chart';
  metric_id: string;
  group_by_dimension_id: string;
  limit?: number;
};

export type TableBlock = BlockBase & {
  type: 'table';
  entity_id: string;
  columns: string[];
  sort_by?: string;
  limit?: number;
};

export type TextBlock = BlockBase & {
  type: 'text';
  content_template: string;
  data_refs?: string[];
};

export type MapBlock = BlockBase & {
  type: 'map';
  metric_id: string;
  geo_dimension_id: string;
};

export type GaugeBlock = BlockBase & {
  type: 'gauge';
  metric_id: string;
  min: number;
  max: number;
  thresholds: Array<{ value: number; color: string }>;
};

export type BlueprintBlock =
  | KPIBlock
  | LineChartBlock
  | BarChartBlock
  | PieChartBlock
  | TableBlock
  | TextBlock
  | MapBlock
  | GaugeBlock;

export type DashboardLayout = {
  cols: number;
  row_height: number;
  margin: [number, number];
};

export type DashboardBlueprint = {
  id: string;
  project_id: string;
  schema_id: string;
  version: number;
  layout: DashboardLayout;
  blocks: BlueprintBlock[];
  is_active: boolean;
  regenerated_reason?: string;
  created_at: string;
};

// ---------- Time Series (Layer 2: Ingesta Recurrente) ----------

export type TimeSeriesPoint = {
  id: string;
  project_id: string;
  metric_id: string;
  dimension_values: Record<string, string | number>;
  value: number;
  period_start: string;
  period_end?: string;
  source_file_id?: string;
  created_at: string;
};

// ---------- Insights (Layer 4: Inteligencia) ----------

export type InsightType = 'weekly' | 'monthly' | 'alert' | 'anomaly';

export type Insight = {
  id: string;
  project_id: string;
  type: InsightType;
  title: string;
  content: string;
  data_snapshot?: Record<string, unknown>;
  model_used?: 'opus-4-7' | 'opus-4-6' | 'sonnet-4-6' | 'haiku-4-5';
  generated_at: string;
  read_at?: string;
  priority: number;
};

// ---------- External Data Cache ----------

export type ExternalDataCache = {
  id: string;
  project_id: string;
  source: string;
  query_key: string;
  query_params?: Record<string, unknown>;
  response: Record<string, unknown>;
  fetched_at: string;
  expires_at: string;
};

// ---------- Schema Evolution + Connectors ----------

export type SchemaEvolutionLog = {
  id: string;
  project_id: string;
  old_version: number;
  new_version: number;
  change_type: 'metric_added' | 'metric_removed' | 'entity_added' | 'entity_removed' | 'rule_updated' | 'identity_updated';
  description?: string;
  triggered_by?: string;
  changed_at: string;
};

export type ConnectorType = 'google_drive' | 'dropbox' | 'onedrive' | 'google_sheets' | 'gmail' | 'whatsapp';

export type DataConnector = {
  id: string;
  project_id: string;
  type: ConnectorType;
  credentials: Record<string, unknown>;
  config?: Record<string, unknown>;
  is_active: boolean;
  last_sync_at?: string;
  created_at: string;
};

// ---------- Files ----------

export type FileRecord = {
  id: string;
  project_id: string;
  user_id: string;
  storage_path: string;
  file_name: string;
  file_type: string;
  file_size: number;
  status: 'uploaded' | 'analyzing' | 'analyzed' | 'failed';
  structural_map?: Record<string, unknown>;
  extracted_data?: Record<string, unknown>;
  error_message?: string;
  uploaded_at: string;
  analyzed_at?: string;
};

// ---------- Projects + Profiles ----------

export type Tier = 'freemium' | 'pro' | 'enterprise';

export type Profile = {
  id: string;
  email: string;
  full_name?: string;
  tier: Tier;
  created_at: string;
  updated_at: string;
};

export type Project = {
  id: string;
  user_id: string;
  name: string;
  description?: string;
  created_at: string;
  updated_at: string;
};
