// ============================================================
// VIZME V5 — Domain types (single source of truth)
// Generated by Opus, consumed by repos / UI / Edge Functions.
// ============================================================

import type { Json } from './database.types';
export type { Json };

// ---------- Business Schema (Layer 1: Modelado) ----------

export type BusinessIdentity = {
  industry: string;
  sub_industry?: string;
  business_model: string;
  size: 'micro' | 'small' | 'medium' | 'large';
  location?: { country: string; state?: string; city?: string };
  language: string;
  currency: string;
};

export type Entity = {
  id: string;
  name: string;
  type: 'transactional' | 'master' | 'reference';
  fields: Array<{
    name: string;
    type: 'string' | 'number' | 'date' | 'boolean' | 'enum';
    required?: boolean;
    enum_values?: string[];
  }>;
};

export type MetricFilterOp = '=' | '!=' | 'in' | 'not_in';

export type MetricFilter = {
  field: string;
  op: MetricFilterOp;
  value: string | number | Array<string | number>;
};

export type Metric = {
  id: string;
  name: string;
  description: string;
  formula: string;
  unit: string;
  aggregation: 'sum' | 'avg' | 'count' | 'min' | 'max' | 'ratio';
  format: 'currency' | 'number' | 'percent' | 'duration';
  good_direction: 'up' | 'down';
  expected_range?: { min: number; max: number };
  // Sprint 4.3: optional pre-aggregation filter, e.g.
  //   { field: 'CANCELADO', op: '=', value: 'FALSO' }
  // applied to source rows before bucketing in ingestEngine.
  filter?: MetricFilter;
};

export type Dimension = {
  id: string;
  name: string;
  type: 'time' | 'category' | 'geo';
  hierarchy?: string[];
};

export type ExtractionRule = {
  source_pattern: string;
  target_entity: string;
  field_mappings: Record<string, string>;
  validations?: Array<{ field: string; rule: string }>;
};

export type ExternalSource = {
  type: 'google_places' | 'inegi' | 'denue' | 'banxico' | 'google_trends' | 'openweather' | 'sat_dof';
  query_template: string;
  refresh_interval_days: number;
  enabled: boolean;
};

export type BusinessSchema = {
  id: string;
  project_id: string;
  version: number;
  business_identity: BusinessIdentity;
  entities: Entity[];
  metrics: Metric[];
  dimensions: Dimension[];
  extraction_rules: ExtractionRule[];
  external_sources: ExternalSource[];
  kpi_targets?: Json;
  model_used: string;
  tokens_input?: number;
  tokens_output?: number;
  created_at: string;
  updated_at: string;
};

// ---------- Dashboard Blueprint (Layer 3: Dashboard Vivo) ----------

type BlockBase = {
  id: string;
  title: string;
  position: { x: number; y: number; w: number; h: number };
};

export type KPIBlock = BlockBase & {
  type: 'kpi';
  metric_id: string;
  comparison?: 'previous_period' | 'previous_year' | 'target';
  target_value?: number;
};

export type LineChartBlock = BlockBase & {
  type: 'line_chart';
  metric_ids: string[];
  dimension_id: string;
  time_range: 'last_7d' | 'last_30d' | 'last_90d' | 'last_year' | 'all';
};

export type BarChartBlock = BlockBase & {
  type: 'bar_chart';
  metric_id: string;
  group_by_dimension_id: string;
  orientation: 'vertical' | 'horizontal';
  limit?: number;
};

export type PieChartBlock = BlockBase & {
  type: 'pie_chart';
  metric_id: string;
  group_by_dimension_id: string;
  limit?: number;
};

export type TableBlock = BlockBase & {
  type: 'table';
  entity_id: string;
  columns: string[];
  sort_by?: string;
  limit?: number;
};

export type TextBlock = BlockBase & {
  type: 'text';
  content_template: string;
  data_refs?: string[];
};

export type MapBlock = BlockBase & {
  type: 'map';
  metric_id: string;
  geo_dimension_id: string;
};

export type GaugeBlock = BlockBase & {
  type: 'gauge';
  metric_id: string;
  min: number;
  max: number;
  thresholds: Array<{ value: number; color: string }>;
};

export type BlueprintBlock =
  | KPIBlock
  | LineChartBlock
  | BarChartBlock
  | PieChartBlock
  | TableBlock
  | TextBlock
  | MapBlock
  | GaugeBlock;

export type DashboardLayout = {
  cols: number;
  row_height: number;
  margin: [number, number];
};

// ---------- Dashboard Blueprint v2 (Sprint 4 — multi-page) ----------
// Opus 4.7 decides how many pages a project needs (simple/medium/complex)
// and emits the full structure as `pages`. Legacy `blocks` + `layout`
// stay for backward compat with v1 blueprints already in DB.

export type VisualizationType =
  | 'kpi_hero'
  | 'kpi_card'
  | 'line_chart'
  | 'area_chart'
  | 'bar_chart'
  | 'bar_horizontal'
  | 'bar_stacked'
  | 'donut_chart'
  | 'heatmap_grid'
  | 'heatmap_calendar'
  | 'scatter_chart'
  | 'composed_chart'
  | 'sparkline'
  | 'gauge'
  | 'radial_bar'
  | 'funnel_chart'
  | 'treemap'
  | 'sankey'
  | 'data_table';

export type SectionType = 'hero' | 'kpi_row' | 'chart_grid' | 'insight_card' | 'data_table';

export type ColorScheme = 'navy' | 'coral' | 'orange' | 'mixed';

export type ValueFormat = 'number' | 'currency' | 'percent' | 'date' | 'string';

export type AxisConfig = {
  field: string;
  label: string;
  format: ValueFormat;
  unit: string | null;
};

export type ChartConfig = {
  x_axis: AxisConfig | null;
  y_axis: AxisConfig | null;
  color_scheme: ColorScheme;
  show_legend: boolean;
  show_grid: boolean;
  aggregation: 'sum' | 'avg' | 'count' | 'max' | 'min' | null;
  sort_by: string | null;
  sort_order: 'asc' | 'desc' | null;
  limit: number | null;
  custom: Record<string, unknown>;
};

export type GridLayout = {
  columns: number;
  gap: 'sm' | 'md' | 'lg';
};

export type GridPosition = {
  column_span: number;
  row_span: number;
};

export type DashboardWidget = {
  id: string;
  type: VisualizationType;
  title: string;
  subtitle: string | null;
  metric_ids: string[];
  dimension_ids: string[];
  chart_config: ChartConfig;
  grid_position: GridPosition;
  insight: string | null;
  priority: number;
};

export type DashboardSection = {
  id: string;
  type: SectionType;
  title: string | null;
  subtitle: string | null;
  widgets: DashboardWidget[];
  grid_layout: GridLayout;
};

export type DashboardPage = {
  id: string;
  title: string;
  icon: string;
  description: string;
  audience: string;
  priority: number;
  sections: DashboardSection[];
};

export type SophisticationLevel = 'simple' | 'medium' | 'complex';

export type DashboardBlueprint = {
  id: string;
  project_id: string;
  schema_id: string;
  version: number;

  // Legacy v1 (still stored in older rows)
  layout?: DashboardLayout;
  blocks?: BlueprintBlock[];

  // v2 (Sprint 4)
  pages: DashboardPage[];
  layout_strategy?: string;
  opus_reasoning?: string;
  sophistication_level?: SophisticationLevel;
  total_widgets?: number;
  model_used?: string;
  tokens_input?: number | null;
  tokens_output?: number | null;
  generation_duration_ms?: number | null;

  is_active: boolean;
  regenerated_reason?: string;
  created_at: string;
  updated_at?: string;

  // Health (Sprint 4.2)
  health_status?: 'complete' | 'partial' | 'limited' | 'no_data' | null;
  health_details?: {
    extracted: number;
    total: number;
    percent: number;
    missing_metric_ids: string[];
    missing_metric_names: string[];
    reasons: string[];
  } | null;
  last_calculated_at?: string | null;
};

// ---------- Metric Calculations Cache (Sprint 4) ----------

export type MetricCalculationPeriod =
  | 'all_time'
  | 'last_year'
  | 'last_quarter'
  | 'last_month'
  | 'last_week';

export type MetricCalculationValue = {
  value: number | null;
  count: number;
  change_percent: number | null;
  change_direction: 'up' | 'down' | 'neutral' | null;
  breakdown_by_dimension: Record<string, Array<{ key: string; value: number }>>;
  time_series: Array<{ date: string; value: number }> | null;
};

export type MetricCalculation = {
  id: string;
  project_id: string;
  metric_id: string;
  period: MetricCalculationPeriod;
  value: MetricCalculationValue;
  calculated_at: string;
};

// ---------- Time Series (Layer 2: Ingesta Recurrente) ----------

export type TimeSeriesPoint = {
  id: string;
  project_id: string;
  metric_id: string;
  dimension_values: Json;
  value: number;
  period_start: string;
  period_end?: string;
  source_file_id?: string;
  created_at: string;
};

// ---------- Insights (Layer 4: Inteligencia) ----------

export type InsightType =
  | 'weekly'
  | 'monthly'
  | 'alert'
  | 'anomaly'
  | 'opportunity'
  | 'risk'
  | 'trend';

export type Insight = {
  id: string;
  project_id: string;
  type: InsightType;
  title: string;
  content: string;
  data_snapshot?: Json;
  model_used?: string;
  generated_at: string;
  read_at?: string;
  priority: number;
  page_id?: string | null;
  metric_references?: string[];
};

// ---------- External Data Cache ----------

export type ExternalDataCache = {
  id: string;
  project_id: string;
  source: string;
  query_key: string;
  query_params?: Json;
  response: Json;
  fetched_at: string;
  expires_at: string;
};

// ---------- Schema Evolution + Connectors ----------

export type SchemaEvolutionLog = {
  id: string;
  project_id: string;
  old_version: number;
  new_version: number;
  change_type: 'metric_added' | 'metric_removed' | 'entity_added' | 'entity_removed' | 'rule_updated' | 'identity_updated';
  description?: string;
  triggered_by?: string;
  changed_at: string;
};

export type ConnectorType = 'google_drive' | 'dropbox' | 'onedrive' | 'google_sheets' | 'gmail' | 'whatsapp';

export type DataConnector = {
  id: string;
  project_id: string;
  type: ConnectorType;
  credentials: Json;
  config?: Json;
  is_active: boolean;
  last_sync_at?: string;
  created_at: string;
};

// ---------- Files ----------
// Columnas de migration 02_files.sql. La pertenencia se infiere
// vía projects.user_id (no hay user_id directo en files).
export type FileRecord = {
  id: string;
  project_id: string;
  storage_path: string;
  file_name: string;
  mime_type?: string;
  file_size_bytes?: number;
  structural_map?: Json;
  extracted_data?: Json;
  uploaded_at: string;
  processed_at?: string;
};

// ---------- Projects + Profiles ----------

export type Tier = 'freemium' | 'pro' | 'enterprise';

export type Profile = {
  id: string;
  email: string;
  full_name?: string;
  tier: Tier;
  trial_ends_at?: string;
  subscription_id?: string;
  created_at: string;
  updated_at: string;
};

export type Project = {
  id: string;
  user_id: string;
  name: string;
  description?: string;
  question?: string;
  created_at: string;
  updated_at: string;
};
